import {CommonSet} from "./CommonSet";
import {CLASSICS_COMMON_SET, CLASSICS_COMMON_SET_UPDATED} from "./classics";
import {LEGENDS_COMMON_SET, LEGENDS_COMMON_SET_UPDATED} from "./legends";
import {HORIZONS_COMMON_SET} from "./horizons";
import {COMMON_TRADE_ROUTES} from "./tradeRoutes";
import {
    MIXED_SET_A_NEW_BEGINNING,
    MIXED_SET_CLASH_OF_LEGACIES,
    MIXED_SET_RISE_OF_CIVILISATIONS, MIXED_SET_THE_GOLDEN_AGES, MIXED_SET_WAY_OF_THE_CONQUEROR
} from "./thematicMixedSets";

export const ALL_COMMON_SET_MANIFEST: Array<CommonSet> = [
    CLASSICS_COMMON_SET,
    LEGENDS_COMMON_SET,
    CLASSICS_COMMON_SET_UPDATED,
    LEGENDS_COMMON_SET_UPDATED,
    HORIZONS_COMMON_SET,
    MIXED_SET_A_NEW_BEGINNING,
    MIXED_SET_RISE_OF_CIVILISATIONS,
    MIXED_SET_CLASH_OF_LEGACIES,
    MIXED_SET_THE_GOLDEN_AGES,
    MIXED_SET_WAY_OF_THE_CONQUEROR,
    COMMON_TRADE_ROUTES
]
