import { ModuleManifest } from "./ModuleManifest";

export const ALL_MODULE_MANIFEST: Array<ModuleManifest> = [
    CLASSICS_COMMON_CARD_MANIFEST,
    CAR_CARD_MANIFEST,
    // CEL_CARD_MANIFEST,
    // GRE_CARD_MANIFEST,
    // MAC_CARD_MANIFEST,
    // PER_CARD_MANIFEST,
    ROM_CARD_MANIFEST,
    // SCY_CARD_MANIFEST,
    // VIK_CARD_MANIFEST,

    // LEGENDS_COMMON_CARD_MANIFEST,
    // ART_CARD_MANIFEST,
    // ATL_CARD_MANIFEST,
    // EGY_CARD_MANIFEST,
    // MAU_CARD_MANIFEST,
    // MIN_CARD_MANIFEST,
    // OLM_CARD_MANIFEST,
    // QIN_CARD_MANIFEST,
    // UTO_CARD_MANIFEST,

    // HORIZONS_UPDATED_COMMON_CARD_MANIFEST,

    // HORIZONS_COMMON_CARD_MANIFEST,
    // CUL_CARD_MANIFEST,
    // INU_CARD_MANIFEST,
    // JPN_CARD_MANIFEST,
    // MAG_CARD_MANIFEST,
    // MAY_CARD_MANIFEST,
    // MRT_CARD_MANIFEST,
    // POL_CARD_MANIFEST,
    // TAI_CARD_MANIFEST,

    // TRADE_ROUTE_EXPANSION_CARD_MANIFEST,
    // ABB_CARD_MANIFEST,
    // AKS_CARD_MANIFEST,
    // GUP_CARD_MANIFEST,
    // SAS_CARD_MANIFEST,
    // TAN_CARD_MANIFEST,
    // WAG_CARD_MANIFEST,
];