import {CommonSet, CommonSetName} from "./CommonSet";
import {CardName} from "../../common/cards/CardName";

export const LEGENDS_COMMON_SET: CommonSet = {
    setName: CommonSetName.LEGENDS,
    includeHorizons: false,
    fame: [
        CardName.IMPERIAL,
        CardName.INDEPENDENT,
        CardName.MAGNIFICENT,
        CardName.OUTSTANDING,
        CardName.PROUD,
        CardName.PROUD1,
        CardName.EMINENT,
        CardName.ACCLAIMED
    ],
    uncivilised: [
        CardName.JADE_MASK_L,
        CardName.ELDERS_L,
        CardName.ESPIONAGE,
        CardName.INVASION_L,
        CardName.MONUMENT,
        CardName.CODE_OF_LAWS,
        CardName.RELIGION,
        CardName.ORACLE_L,
        CardName.DOMESTICATION,
        CardName.WATER_MILL,
        CardName.QANAT,
        CardName.CITY_L1,
        CardName.CITY_L2,
        CardName.CITY_L3,
        CardName.ROAD_BUILDING,
        CardName.ART,
        CardName.DIPLOMACY_L,
        CardName.LEADERSHIP_L
    ],
    civilised: [
        CardName.EDUCATION_L,
        CardName.MONEYLENDER_L,
        CardName.CORRUPTION_L,
        CardName.ONAGER_L,
        CardName.METROPOLIS_L,
        CardName.ASTRONOMY,
        CardName.CIVIL_SERVICE,
        CardName.EXPORTS_L,
        CardName.URBAN_DEVELOPMENT_L,
        CardName.MERCENARIES_L,
        CardName.AMPHITHEATRE,
        CardName.CATAPHRACT_L
    ],
    region: [
        CardName.FORTUNATE_ISLE,
        CardName.RAINFOREST,
        CardName.MOUNTAIN_L,
        CardName.PENINSULA,
        CardName.LAKES,
        CardName.HIGHLANDS,
        CardName.LOWLANDS,
        CardName.MOOR,
        CardName.PLAIN,
        CardName.ARCHIPELAGO,
        CardName.FORTIFIED_REGION,
        CardName.GRASSLAND,
        CardName.ISLAND
    ],
    tributary: [
        CardName.ETRUSCANS,
        CardName.SCYTHIANS,
        CardName.VIKINGS,
        CardName.PHOENICIANS,
        CardName.GREEKS,
        CardName.CARTHAGINIANS,
        CardName.PERSIANS,
        CardName.CELTS,
        CardName.MACEDONIANS
    ],
    tradeRoute: [],
    threePlayerAdd: [
        CardName.RITUALS_N_CEREMONIES_L,
        CardName.CITY_L,
        CardName.LOST_SCROLL_L,
        CardName.CARTOGRAPHY,
        CardName.SACRED_GROVE,
        CardName.ROMANS,
    ],
    fourPlayerAdd: [
        CardName.MINING,
        CardName.DRAMA_N_POETRY_L,
        CardName.MASONRY,
        CardName.XIONGNU
    ],
    alternativeTributary: [],
    tradeRouteExpansionRemove: [],
    tradeRouteExpansionAdd: [],
}

export const LEGENDS_COMMON_SET_UPDATED: CommonSet = {
    setName: CommonSetName.LEGENDS_UPDATED,
    includeHorizons: true,
    fame: [
        CardName.IMPERIAL,
        CardName.INDEPENDENT,
        CardName.MAGNIFICENT,
        CardName.OUTSTANDING,
        CardName.PROUD,
        CardName.PROUD1,
        CardName.EMINENT,
        CardName.ACCLAIMED
    ],
    uncivilised: [
        CardName.JADE_MASK_L_NEW,
        CardName.ELDERS_L,
        CardName.ESPIONAGE,
        CardName.INVASION_L_NEW,
        CardName.MONUMENT,
        CardName.CODE_OF_LAWS,
        CardName.RELIGION_NEW,
        CardName.ORACLE_L,
        CardName.DOMESTICATION,
        CardName.WATER_MILL,
        CardName.QANAT,
        CardName.CITY_L1,
        CardName.CITY_L2,
        CardName.CITY_L3,
        CardName.ROAD_BUILDING,
        CardName.ART,
        CardName.DIPLOMACY_L,
        CardName.LEADERSHIP_L
    ],
    civilised: [
        CardName.EDUCATION_L,
        CardName.MONEYLENDER_L,
        CardName.CORRUPTION_L,
        CardName.ONAGER_L,
        CardName.METROPOLIS_L,
        CardName.ASTRONOMY,
        CardName.CIVIL_SERVICE,
        CardName.EXPORTS_L,
        CardName.URBAN_DEVELOPMENT_L,
        CardName.MERCENARIES_L,
        CardName.AMPHITHEATRE,
        CardName.CATAPHRACT_L
    ],
    region: [
        CardName.FORTUNATE_ISLE,
        CardName.RAINFOREST,
        CardName.PEAK_L_NEW,
        CardName.PENINSULA_NEW,
        CardName.LAKES,
        CardName.HIGHLANDS,
        CardName.LOWLANDS_NEW,
        CardName.MOOR,
        CardName.PLAIN,
        CardName.ARCHIPELAGO_NEW,
        CardName.FORTIFIED_REGION_NEW,
        CardName.GRASSLAND,
        CardName.ISLAND_NEW
    ],
    tributary: [
        CardName.ETRUSCANS,
        CardName.SCYTHIANS,
        CardName.VIKINGS,
        CardName.PHOENICIANS,
        CardName.GREEKS,
        CardName.CARTHAGINIANS,
        CardName.PERSIANS,
        CardName.CELTS_NEW,
        CardName.MACEDONIANS
    ],
    tradeRoute: [],
    threePlayerAdd: [
        CardName.RITUALS_N_CEREMONIES_L,
        CardName.CITY_L,
        CardName.LOST_SCROLL_L,
        CardName.CARTOGRAPHY,
        CardName.SACRED_GROVE,
        CardName.ROMANS,
    ],
    fourPlayerAdd: [
        CardName.MINING,
        CardName.DRAMA_N_POETRY_L,
        CardName.MASONRY,
        CardName.XIONGNU
    ],
    alternativeTributary: [],
    tradeRouteExpansionRemove: [],
    tradeRouteExpansionAdd: [],
}
